name: Run Ungoliant

on:
  push:
    branches:
      - colab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Scrapy
        run: pip install Scrapy
      
      - name: List directories
        run: ls -R

      - name: Run Scrapy spider
        run: |
          scrapy crawl ungoliant
        working-directory: AbyssalWebSpinner/WebSpinnerLair/CreepyCrawller/CreepyCrawller

      - name: Upload CSV as artifact
        uses: actions/upload-artifact@v4
        with:
          name: stock-csv-file
          path: AbyssalWebSpinner/WebSpinnerLair/CreepyCrawller/CreepyCrawller/spiders/stockCsvFile.csv
